/*
  # Seed SKU Items Data

  1. Data Seeding
    - Inserts 106 Sari Roti SKU items into the sku_items table
    - Covers categories: Roti Tawar, Sandwich, Zupper Sandwich,
      Bun & Sobek, Roti Krim, Zuperr Creamy, Dorayaki,
      Roti Kasur & Sisir, Cake, Lapis Surabaya, Soft Cake,
      Steam Cheese Cake, Sari Choco, Bamkohem
    - Each item has kode, nama, kategori, and cbp (price)
    - All items are set to is_active = true

  2. Important Notes
    - Uses ON CONFLICT to avoid duplicate inserts if run again
    - Only inserts if the kode does not already exist
*/

INSERT INTO sku_items (kode, nama, kategori, cbp, is_active) VALUES
  ('RTS', 'Roti Tawar Special', 'Roti Tawar', 15000, true),
  ('RTG', 'Roti Tawar Gandum', 'Roti Tawar', 18000, true),
  ('RTPDM', 'Roti Tawar Pandan Manis', 'Roti Tawar', 18000, true),
  ('RCC', 'Roti Tawar Choco Chip', 'Roti Tawar', 19000, true),
  ('RTKL', 'Roti Tawar Klasik', 'Roti Tawar', 12500, true),
  ('RKU', 'Roti Tawar Kupas', 'Roti Tawar', 6000, true),
  ('RJKU', 'Roti Jumbo Tawar Kupas', 'Roti Tawar', 21000, true),
  ('DOP', 'Roti Tawar Doble Soft F', 'Roti Tawar', 14500, true),
  ('DOM', 'Roti Tawar Doble Soft', 'Roti Tawar', 20500, true),
  ('RTJS', 'Roti Tawar Jumbo Spesial', 'Roti Tawar', 18000, true),
  ('RJMS', 'Roti Jumbo Milk Soft', 'Roti Tawar', 17500, true),
  ('SCC', 'Sandwich Coklat', 'Sandwich', 6000, true),
  ('SAB', 'Sandwich Blueberry', 'Sandwich', 6000, true),
  ('SAP', 'Sandwich Krim Peanut', 'Sandwich', 6000, true),
  ('SKI', 'Sandwich Keju', 'Sandwich', 6000, true),
  ('SMG', 'Sandwich Margarin Gula', 'Sandwich', 6000, true),
  ('SSM', 'Sandwich Pandan Sarikaya', 'Sandwich', 6000, true),
  ('SCB', 'Sandwich Choco Blast', 'Sandwich', 6000, true),
  ('ZSCCK', 'Zupper Sandwich Krim Coklat', 'Zupper Sandwich', 5000, true),
  ('ZSCMK', 'Zupper Sandwich Krim Moka', 'Zupper Sandwich', 5000, true),
  ('ZSCS', 'Zupper Sandwich Creamy Sweet', 'Zupper Sandwich', 5000, true),
  ('ZSCST', 'Zuper Sandwich Krim Strawberry', 'Zupper Sandwich', 5000, true),
  ('ICK GT', 'Choco Bun', 'Bun & Sobek', 4000, true),
  ('ICZ GT', 'Cheese Bun', 'Bun & Sobek', 4000, true),
  ('ICE', 'Sweet Cheese Bun', 'Bun & Sobek', 4000, true),
  ('IST', 'Blueberry Bun GT', 'Bun & Sobek', 4000, true),
  ('IBL', 'Blueberry Bun', 'Bun & Sobek', 4000, true),
  ('ICO', 'Coconut Bun GT', 'Bun & Sobek', 4000, true),
  ('TOC', 'Roti Sobek Coklat Coklat', 'Bun & Sobek', 18000, true),
  ('TCC', 'Roti Sobek Coklat Meses', 'Bun & Sobek', 18000, true),
  ('TCS', 'Roti Sobek Coklat Sarikaya', 'Bun & Sobek', 18000, true),
  ('TST', 'Roti Sobek Coklat Strawberry', 'Bun & Sobek', 18000, true),
  ('TCB', 'Roti Sobek Coklat Blueberry', 'Bun & Sobek', 13500, true),
  ('TCBIII', 'Roti Sobek Krim Meses', 'Bun & Sobek', 13500, true),
  ('TDST', 'Sobek Duo Strawberry', 'Bun & Sobek', 11000, true),
  ('TDCB', 'Sobek Duo Blueberry', 'Bun & Sobek', 11000, true),
  ('TDOC', 'Sobek Duo Cokelat', 'Bun & Sobek', 8500, true),
  ('TDSA', 'Sobek Duo Sarikaya', 'Bun & Sobek', 8000, true),
  ('KBC', 'Klasik Bantal Sweet Cheese', 'Bun & Sobek', 8500, true),
  ('RMNS', 'Roti Mini Strawberry', 'Bun & Sobek', 8000, true),
  ('BUR', 'Burgerbun', 'Bun & Sobek', 11000, true),
  ('SRPL', 'Plain Rolls', 'Bun & Sobek', 11000, true),
  ('SCM', 'Roti Krim Cokelat Meses', 'Roti Krim', 5000, true),
  ('SCCIII', 'Roti Creamy Cokelat Meses', 'Roti Krim', 5000, true),
  ('SCVIII', 'Roti Krim Coklat', 'Roti Krim', 5000, true),
  ('SCCJII', 'Roti Krim Keju', 'Roti Krim', 5000, true),
  ('SRMIII', 'Roti Krim Moca', 'Roti Krim', 5000, true),
  ('ZCRCK', 'Zuperr Creamy Choco Double Choco', 'Zuperr Creamy', 5000, true),
  ('ZCRCR', 'Zuperr Creamy Choco Choco Berry', 'Zuperr Creamy', 5000, true),
  ('ZCRCB', 'Zuperr Creamy Choco Choco Banana', 'Zuperr Creamy', 5000, true),
  ('SRS', 'Roti Sandroll Zuperr Creamy Strawberry', 'Zuperr Creamy', 5000, true),
  ('DCS', 'Dorayaki Si Coklat', 'Dorayaki', 7500, true),
  ('DCP', 'Dorayaki Choco Peanut', 'Dorayaki', 7500, true),
  ('DCH', 'Dorayaki Hokkaido Cheese', 'Dorayaki', 7500, true),
  ('DHF', 'Dorayaki Honey Flavor', 'Dorayaki', 7500, true),
  ('DSK', 'Dorayaki Sarikaya', 'Dorayaki', 5500, true),
  ('DMT', 'Dorayaki Martabak', 'Dorayaki', 6000, true),
  ('DPS', 'Dorayaki Pandan Sarikaya', 'Dorayaki', 6000, true),
  ('DNS', 'Dorayaki Nastar', 'Dorayaki', 6000, true),
  ('RKJ', 'Roti Kasur Keju', 'Roti Kasur & Sisir', 14000, true),
  ('RSM', 'Roti Sisir Mentega', 'Roti Kasur & Sisir', 11000, true),
  ('RKS', 'Roti Kasur Susu', 'Roti Kasur & Sisir', 11000, true),
  ('CCC', 'Chiffon Cake Coklat', 'Cake', 25000, true),
  ('CCP', 'Chiffon Cake Pandan', 'Cake', 25000, true),
  ('MCP VI', 'Mini Cupcake Vanilla Coconut Isi 6', 'Cake', 22000, true),
  ('KAOF', 'Kastela Original Family', 'Cake', 255000, true),
  ('KAOM', 'Kastela Original Medium', 'Cake', 105000, true),
  ('BKV', 'Bolu Kukus Putih Vanilla', 'Cake', 12500, true),
  ('BMO', 'Bolu Mini Original', 'Cake', 5000, true),
  ('WFO', 'Waffle Original', 'Cake', 5000, true),
  ('LSPO', 'Lapis Surabaya Premium Original', 'Lapis Surabaya', 12500, true),
  ('LSPK', 'Lapis Surabaya Premium Keju', 'Lapis Surabaya', 12500, true),
  ('LSPP', 'Lapis Surabaya Premium Pandan', 'Lapis Surabaya', 12500, true),
  ('LSPM', 'Lapis Surabaya Premium Moca', 'Lapis Surabaya', 12500, true),
  ('SCCP', 'Soft Cake Putu Pandan', 'Soft Cake', 9500, true),
  ('SCPI', 'Soft Cake Pisang Ijo', 'Soft Cake', 9500, true),
  ('SCET', 'Soft Cake Es Teler', 'Soft Cake', 9500, true),
  ('SCGA', 'Soft Cake Gula Aren', 'Soft Cake', 9500, true),
  ('SCPSM', 'Soft Cake Pandan Salted Caramel Mocca', 'Soft Cake', 9500, true),
  ('STCS', 'Steam Cheese Cake Strawberry', 'Steam Cheese Cake', 9500, true),
  ('STCC', 'Steam Cheese Cake', 'Steam Cheese Cake', 9500, true),
  ('STCK', 'Steam Cheese Cake Cokelat', 'Steam Cheese Cake', 9500, true),
  ('STCB', 'Steam Cheese Cake Banana', 'Steam Cheese Cake', 9500, true),
  ('STCTM', 'Steam Cheese Cake Tiramisu', 'Steam Cheese Cake', 9500, true),
  ('STCBA', 'Steam Cheese Cake Basket', 'Steam Cheese Cake', 9500, true),
  ('STCDC', 'Steam Cheese Cake Duo', 'Steam Cheese Cake', 7000, true),
  ('SCSC', 'Sari Choco Spread Coklat', 'Sari Choco', 18000, true),
  ('SCSCH', 'Sari Choco Spread Coklat Hazelnut', 'Sari Choco', 18000, true),
  ('SCM110', 'Sari Choco Milk 110ml', 'Sari Choco', 5000, true),
  ('SCM180', 'Sari Choco Milk 180ml', 'Sari Choco', 6000, true),
  ('BKCK', 'Bamkohem Original', 'Bamkohem', 10500, true),
  ('BKKJ', 'Bamkohem Keju', 'Bamkohem', 10500, true)
ON CONFLICT (kode) DO NOTHING;
